# Generated by Django 4.2.4 on 2023-08-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
