# Generated by Django 4.2.2 on 2023-06-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClassRoom', '0006_participantroomsettings_delete_studentroomsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.classroom')),
            ],
        ),
    ]
