# Generated by Django 4.2.2 on 2023-06-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
