# Generated by Django 4.2.2 on 2023-06-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0002_rename_topics_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
    ]
