# Generated by Django 4.2.2 on 2023-06-26 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassRoom', '0003_rename_description_topic_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.CreateModel(
            name='StudentRoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_turned', models.BooleanField(default=False)),
                ('video_turned', models.BooleanField(default=False)),
                ('whiteboard_turned', models.BooleanField(default=False)),
                ('audio_permission', models.BooleanField(default=True)),
                ('video_permission', models.BooleanField(default=True)),
                ('whiteboard_permission', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='ClassRoom.participants')),
            ],
        ),
        migrations.AddField(
            model_name='participants',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ClassRoom.classroom'),
        ),
        migrations.AddField(
            model_name='participants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='ClassRoom.participants'),
        ),
    ]
