# Generated by Django 4.2.2 on 2023-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0004_participants_remove_classroom_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='participants',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
