# Generated by Django 4.2.2 on 2023-06-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0005_remove_classroom_lecturer_participants_is_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantRoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_turned', models.BooleanField(default=False)),
                ('video_turned', models.BooleanField(default=False)),
                ('whiteboard_turned', models.BooleanField(default=False)),
                ('audio_permission', models.BooleanField(default=True)),
                ('video_permission', models.BooleanField(default=True)),
                ('whiteboard_permission', models.BooleanField(default=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='ClassRoom.participants')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRoomSettings',
        ),
    ]
