# Generated by Django 4.2.2 on 2023-07-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0006_participantroomsettings_delete_studentroomsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
