# Generated by Django 4.2.3 on 2023-07-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
    ]
